config/routes.rb
Rails.application.routes.draw do

  	post "/event_calendars/create" => "event_calendars#create"
  	get '/event_calendars' => "event_calendars#new" , as:"calendars"

  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  resources :notes, only: [:show, :create, :edit, :update, :destroy]

  root 'home#top'
  get '/about' => 'home#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
	belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :start, presence: true
	validates :end, presence: true

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :content2, presence: true, length: { maximum: 140 }
  validates :content3, presence: true, length: { maximum: 140 }
  validates :content4, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :validatable
  has_many :notes
  has_many :events

  validates :name, presence: true
  # deviseのvalidatableによって以下と同じバリデーションが設定されているのでコメントアウトしています
  # validates :email, presence: true, uniqueness: true

  def set_image(file)
    if !file.nil?
      file_name = file.original_filename
      File.open("public/user_images/#{file_name}", 'wb'){|f| f.write(file.read)}
      self.image = file_name
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
      
	 before_action :configure_permitted_parameters, if: :devise_controller?
	 
	 include ApplicationHelper

 private
 def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end 

   def default_url_options() {privateIp: '172.17.0.7', containerPort: '3000', languageName: 'rails'}.merge(super) end
end

app/controllers/event_calendars_controller.rb
class EventCalendarsController < ApplicationController

 	 before_action :authenticate_user!

  def new
    @events = [];
    
    Event.all.each do |data|
      @events += [
        'title' => data['title'],
        'start' => data['start'],
        'end'   => data['end'],
        'detail'=> "aaaaaaaaaa",
        'color' => '#28b086'
        ]
    
    gon.events = @events
  end
end  

  def create
  	@event = Event.new
  	@event.title = params[:title]
    @event.start = params[:start]
    @event.end = params[:end]
  	@event.user_id = current_user.id
    if @event.save
  	redirect_to calendars_path(@event.id), notice: "保存されました"
  else
    redirect_to calendars_path(@event.id), notice: "保存失敗：入力した内容に不備があります"
  end
end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    if user_signed_in?
      
      @note = Note.new
     
      @notes = Note.all.order(created_at: :desc)
      
      
    else
      @message = "ようこそJobHuntへ！"
    end
  end
  
  def about
  end
  
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :authenticate_user!
    before_action :correct_user, only: [:edit, :update]
    before_action :set_note, only: [:show, :edit, :update, :destroy]

  

  def show
  end

  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      redirect_to @note, notice: "投稿が保存されました"
    else
      @notes = Note.all.order(created_at: :desc)
      render "home/top"
      
    end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to @note, notice: "投稿が更新されました"
    else
      render :edit
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path
  end

  private

    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:title, :content, :content2, :content3, :content4)
    end

     def correct_user
      note = Note.find(params[:id])
      if !current_user?(note.user)
        redirect_to root_path, alert: '許可されていないページです'
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    before_action :correct_user, only:[:edit, :update]

  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def show
    @notes = @user.notes
  end

  

  def edit
  end
  

  def update
    file = params[:user][:image]
    @user.set_image(file)

    if @user.update(user_params)
      redirect_to @user, notice: 'ユーザー情報が更新されました'
    else
      render :edit
    end
  end


  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email)
    end

    def correct_user
      user = User.find(params[:id])
       if !current_user?(user)
        redirect_to root_path, alert: '許可されていないページです'
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user?(user)
    current_user.id == user.id
  end
end

app/helpers/event_calendars_helper.rb
module EventCalendarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def image_for(user)
    if user.image
      image_tag "/user_images/#{user.image}", class: "profile_img"
    else
      image_tag "dafault.jpg", class: "profile_img"
    end
  end
  
end

app/views/event_calendars/index.html.erb
 <div id="calendar">
<div id="post-modal">
	<div class="modal">
	<div class="close-modal">
        <i class="fa fa-2x fa-times"></i>
      </div>
      <div id="login-form">
        <h2>予定|リマインダー</h2>
        <h3 id="clickday"></h3>  
        <%= form_tag event_calendars_create_path do %>  
          <input name="title" class="form-control form-controler" type="text" placeholder="例：19:00〜22:00A社面接">
          <p>
          開始時間
          </p>
          <input name="start" calss="form-control form-controler"
          type="time">
          <p>
          終了時間
          </p>
          <input name="end" calss="form-control form-controler"
          type="time">
          <input type="submit" value="保存" id="submit-btn" class="btn"></input>
        <% end %>
      </div>
    </div>
</div>

app/views/event_calendars/new.html.erb
 <div id="calendar">
<div id="post-modal">
	<div class="modal">
	<div class="close-modal">
        <i class="fa fa-2x fa-times"></i>
      </div>
      <div id="login-form">
        <h2>予定|リマインダー</h2>
        <h3 id="clickday"></h3>  
        <%= form_tag event_calendars_create_path do %>  
          <input name="title" class="form-control form-controler" type="text" placeholder="例:A社面接">
          <p>
          開始時間
          </p>
          <label>
          <input name="start" step="600" calss="form-control form-controler"
          type="datetime-local">
          </label>
          <p>
          終了時間
          </p>
          <input name="end" step="600" value='"2017-06-01T10:"' calss="form-control form-controler"
          type="datetime-local">
          <input type="submit" value="保存" id="submit-btn" class="btn"></input>
        <% end %>
      </div>
    </div>
</div>

app/views/event_calendars/show.html.erb
 <div id="calendar">
<div id="post-modal">
	<div class="modal">
	<div class="close-modal">
        <i class="fa fa-2x fa-times"></i>
      </div>
      <div id="login-form">
        <h2>予定|リマインダー</h2>
        <h3 id="clickday"></h3>  
        <%= form_tag event_calendars_create_path do %>  
          <input name="title" class="form-control form-controler" type="text" placeholder="例：19:00〜22:00A社面接">
          <p>
          開始時間
          </p>
          <label>
          <input name="start" step="600" calss="form-control form-controler"
          type="datetime-local">
          </label>
          <p>
          終了時間
          </p>
          <input name="end" step="600" value='"2017-06-01T10:"' calss="form-control form-controler"
          type="datetime-local">
          <input type="submit" value="保存" id="submit-btn" class="btn"></input>
        <% end %>
      </div>
    </div>
</div>

app/views/home/about.html.erb
<h1>JobHuntとは？</h1>
<p>就活生の就活の助けとなるツールを無料で提供しているサービスです</p>

app/views/home/top.html.erb
<% if user_signed_in? %>
  <aside class="sidebar">
    <%= render 'notes/form' %>
  </aside>
  <ul class="notes">
    <h2>投稿の一覧</h2>
    <%= render @notes %>
  </ul>
<% else %>
  <div class="top-wrapper">
    <%= image_tag "jobhunt.jpg" %>
    <div class="register-wrapper">
      <h1><%= @message %></h1>
      <%= link_to "新規登録", new_user_registration_path, class: "btn btn-large register-btn" %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobHunt</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= Gon::Base.render_data %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar">
    <div class="container">
      <div id="logo"><%= link_to "JobHunt", root_path %></div>
      <% if user_signed_in? %>
        <ul class="header-right">
          <li><%= link_to "カレンダー", calendars_path, method: :get %></li>
         
          <li><%= link_to current_user.name, current_user %></li>
          
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          
        </ul>
      <% else %>
        <ul class="header-right">
          <li><%= link_to "概要", about_path %></li>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          
          <li><%= link_to "ログイン", new_user_session_path %></li>
    
        </ul>
      <% end %>
      
    </div>
  </header>
  
  <div class="container">

    <p class="alert alert-success">
      <%= notice %>
    </p>
    <p class="alert alert-danger">
      <%= alert %>
    </p>
    <%= yield %>
  </div>

  <div class="container">
    <footer class="footer">
      <div class="small">
        &copy; JobHunt.co
      </div>
    </footer>
  </div>
</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= @note.errors.count %>件のエラー:</h2>

      <ul>
        <% @note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-design-wrapper">
<div class="form-design">
  企業名
  <%= f.text_field :title, {class: "form-control title-field" }  %>
  事業内容
  <%= f.text_area :content, { class: "form-control content-field" } %>
  会社の雰囲気
  <%= f.text_area :content2, { class: "form-control content-field" } %>
  職種ごとの仕事内容
  <%= f.text_area :content3, { class: "form-control content-field" } %>
  会社へ対する評価
  <%= f.text_area :content4, { class: "form-control content-field" } %>
  <%= f.submit "保存", { class: "btn primary-btn" } %>
</div>
</div>
<% end %>

app/views/notes/_note.html.erb
<li>  
  <%= image_for(note.user) %>
  <span class="content">
   企業名： <%= link_to note.title, note_path(note.id) %>
  </span>
  <span>
    <%= "投稿日：" + note.created_at.strftime("%Y-%m-%d") %>
  </span>
</li>

app/views/notes/edit.html.erb
<h1>投稿を編集する</h1>
<%= render 'form' %>

app/views/notes/index.html.erb
<h1>投稿の一覧</h1>
<ul class="notes">
  <%= render @notes %>
</ul>

app/views/notes/new.html.erb
<h1>新規投稿する</h1>
<%= render 'form' %>

app/views/notes/show.html.erb
<p id="notice" class="alert alert-success"></p>

<h2>企業名</h2>
<p><%= @note.title %></p>
<h2>事業内容</h2>
<p><%= @note.content %></p>
<h2>会社の雰囲気</h2>
<p><%= @note.content2 %></p>
<h2>職種ごとの仕事内容</h2>
<p><%= @note.content3 %></p>
<h2>会社へ対する評価</h2>
<p><%= @note.content4 %></p>

<% if current_user?(@note.user) %>
<%= link_to "編集", edit_note_path(@note.id), class: "btn edit-btn" %>
<%= link_to "削除", note_path(@note.id), method: "delete", class: "btn destroy-btn", "data-confirm" => "本当に削除しますか？" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
       <p><%= @user.errors.count %>件のエラーがあります。</p>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  名前
  <%= f.text_field :name, class: "form-control name-field" %>

  メールアドレス
  <%= f.text_field :email, class: "form-control email-field" %>
  
  プロフィール画像
  <%= f.file_field :image, class: "form-control image-field" %>

  <%= f.submit '保存', class: "btn primary-btn" %>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザーの編集</h1>

<%= render 'form' %>

<%= link_to 'ユーザー一覧へ', users_path %>

app/views/users/index.html.erb
<h1 class="heading">ユーザー一覧</h1>


<ul class="user-list">
  <% @users.each do |user| %>
    <li>
      <%= image_for(user) %>
      <%= link_to user.name, user %> |
      <%= user.email %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>新規ユーザー作成</h1>

<%= render 'form' %>

<%= link_to '戻る', users_path %>

app/views/users/show.html.erb
<aside class="sidebar">  
  <section>
    <span class="label">プロフィール画像</span>
    <h3 class="user-info">
      <%= image_for(@user) %>
    </h3>
  </section>

  <section>
    <span class="label">ユーザー</span>
    <h3 class="user-info"><%= @user.name %></h3>
  </section>
  
  <section>
    <span class="label">メールアドレス</span>
    <h3 class="user-info"><%= @user.email %></h3>
  </section>

  <% if current_user?(@user) %>
    <section>
      <small><%= link_to 'プロフィールを編集', edit_user_path(@user) %></small>
    </section>
  <% end %>

</aside>

<ul class="notes">
  <%= render @notes %>
</ul>